version: "3"
services:
  slack-alert:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: weeve-slack-alert
      MODULE_TYPE: EGRESS
      EGRESS_URL: https://hookb.in/DrrdzwQwXgIdNNEwggLo
      INPUT_LABEL: "temperature"
      INPUT_UNIT: "Celsius"
      ALERT_SEVERITY: "warning"
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - 5000:80
